# Generated by Django 4.1.1 on 2022-09-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacitacion', models.CharField(max_length=75, null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('nivel', models.CharField(choices=[('Postgrado', 'Postgrado'), ('Gestion', 'Gestion'), ('Maestria', 'Maestria'), ('Grado', 'Grado'), ('Tecnico', 'Tecnico'), ('Tecnologo', 'Tecnologo')], max_length=12, null=True)),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField()),
                ('institucion', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=50, null=True)),
                ('nivelRiesgo', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=5, null=True)),
                ('nivelMinimoSalario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivelMaximoSalario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50, null=True)),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puestoOcupado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.puestos')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, null=True)),
                ('cedula', models.IntegerField(max_length=11, null=True)),
                ('fechaIngreso', models.DateField()),
                ('departamento', models.CharField(max_length=50, null=True)),
                ('salarioMensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
                ('puesto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.puestos')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(max_length=11, null=True)),
                ('nombre', models.CharField(max_length=75, null=True)),
                ('departamento', models.CharField(max_length=50, null=True)),
                ('salarioAspira', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recomendadoPor', models.CharField(max_length=50)),
                ('experienciaLaboral', models.ManyToManyField(to='system.experiencialaboral')),
                ('principalesCapacitaciones', models.ManyToManyField(to='system.capacitaciones')),
                ('principalesCompetencias', models.ManyToManyField(to='system.competencia')),
                ('puestoAspira', models.ManyToManyField(to='system.puestos')),
            ],
        ),
    ]
