# Generated by Django 4.1.1 on 2022-10-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_capacitaciones_puestos_experiencialaboral_empleados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='fechaDesde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='fechaHasta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='nivel',
            field=models.CharField(choices=[('Tecnologo', 'Tecnologo'), ('Tecnico', 'Tecnico'), ('Gestion', 'Gestion'), ('Postgrado', 'Postgrado'), ('Grado', 'Grado'), ('Maestria', 'Maestria')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechaDesde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechaHasta',
            field=models.DateField(),
        ),
    ]
