# Generated by Django 4.1.1 on 2022-10-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_capacitaciones_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='nivel',
            field=models.CharField(choices=[('Grado', 'Grado'), ('Tecnologo', 'Tecnologo'), ('Tecnico', 'Tecnico'), ('Gestion', 'Gestion'), ('Postgrado', 'Postgrado'), ('Maestria', 'Maestria')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Bajo', 'Bajo'), ('Alto', 'Alto'), ('Medio', 'Medio')], max_length=5, null=True),
        ),
    ]
