# Generated by Django 4.1.1 on 2022-10-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_capacitaciones_nivel_alter_idiomas_idioma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='cedula',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='nivel',
            field=models.CharField(choices=[('Tecnologo', 'Tecnologo'), ('Gestion', 'Gestion'), ('Postgrado', 'Postgrado'), ('Tecnico', 'Tecnico'), ('Grado', 'Grado'), ('Maestria', 'Maestria')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Bajo', 'Bajo'), ('Medio', 'Medio')], max_length=5, null=True),
        ),
    ]
