# Generated by Django 4.1.1 on 2022-10-11 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_candidatos_cedula_alter_capacitaciones_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatos',
            name='puestoAspira',
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='nivel',
            field=models.CharField(choices=[('Tecnico', 'Tecnico'), ('Maestria', 'Maestria'), ('Tecnologo', 'Tecnologo'), ('Postgrado', 'Postgrado'), ('Grado', 'Grado'), ('Gestion', 'Gestion')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='candidatos',
            name='puestoAspira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.puestos'),
        ),
    ]
