# Generated by Django 4.1.1 on 2022-10-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_remove_candidatos_puestoaspira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='nivel',
            field=models.CharField(choices=[('Tecnologo', 'Tecnologo'), ('Gestion', 'Gestion'), ('Tecnico', 'Tecnico'), ('Postgrado', 'Postgrado'), ('Grado', 'Grado'), ('Maestria', 'Maestria')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Bajo', 'Bajo'), ('Alto', 'Alto'), ('Medio', 'Medio')], max_length=5, null=True),
        ),
    ]
