# Generated by Django 4.1.1 on 2022-10-12 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0013_alter_capacitaciones_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatos',
            name='user',
        ),
        migrations.AddField(
            model_name='candidatos',
            name='createdBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='nivel',
            field=models.CharField(choices=[('Gestion', 'Gestion'), ('Grado', 'Grado'), ('Postgrado', 'Postgrado'), ('Tecnico', 'Tecnico'), ('Tecnologo', 'Tecnologo'), ('Maestria', 'Maestria')], max_length=12, null=True),
        ),
    ]
