# Generated by Django 4.1.1 on 2022-10-12 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_remove_candidatos_user_candidatos_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='nivel',
            field=models.CharField(choices=[('Postgrado', 'Postgrado'), ('Maestria', 'Maestria'), ('Tecnico', 'Tecnico'), ('Grado', 'Grado'), ('Gestion', 'Gestion'), ('Tecnologo', 'Tecnologo')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.puestos'),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Bajo', 'Bajo'), ('Medio', 'Medio')], max_length=5, null=True),
        ),
    ]
