# Generated by Django 4.1.1 on 2022-10-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_alter_capacitaciones_nivel_alter_empleados_puesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='nivel',
            field=models.CharField(choices=[('Maestria', 'Maestria'), ('Grado', 'Grado'), ('Tecnico', 'Tecnico'), ('Tecnologo', 'Tecnologo'), ('Postgrado', 'Postgrado'), ('Gestion', 'Gestion')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=5, null=True),
        ),
    ]
