# Generated by Django 4.1.1 on 2022-10-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_alter_capacitaciones_nivel_alter_puestos_nivelriesgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='nivel',
            field=models.CharField(choices=[('Gestion', 'Gestion'), ('Postgrado', 'Postgrado'), ('Tecnologo', 'Tecnologo'), ('Maestria', 'Maestria'), ('Tecnico', 'Tecnico'), ('Grado', 'Grado')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Medio', 'Medio'), ('Bajo', 'Bajo'), ('Alto', 'Alto')], max_length=5, null=True),
        ),
    ]
