# Generated by Django 4.1.1 on 2022-10-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_alter_capacitaciones_nivel_alter_puestos_nivelriesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatos',
            name='idioma',
            field=models.ManyToManyField(to='system.idiomas'),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='nivel',
            field=models.CharField(choices=[('Tecnico', 'Tecnico'), ('Maestria', 'Maestria'), ('Tecnologo', 'Tecnologo'), ('Gestion', 'Gestion'), ('Grado', 'Grado'), ('Postgrado', 'Postgrado')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Medio', 'Medio'), ('Alto', 'Alto'), ('Bajo', 'Bajo')], max_length=5, null=True),
        ),
    ]
